export enum EnumQuestionType {
    Distinction = "Distinction",
    ComparisonNumerical = "Comparison Numerical",
    ComparisonChronological = "Comparison Chronological",
    Syllogism = "Syllogism",
    Direction = "Direction",
    Direction3DSpatial = "Direction3D Spatial",
    Direction3DTemporal = "Direction3D Temporal",
    LinearArrangement = "Linear Arrangement",
    CircularArrangement = "Circular Arrangement",
    GraphMatching = "Graph Matching",
    Analogy = "Analogy",
    Binary = "Binary",
}

// TRADUCTION FR (ajout par rapport au dépôt d'origine) : ces valeurs sont
// affichées telles quelles dans les prémisses. Le marqueur « # steps » est
// remplacé par « immédiatement » ou « à N pas » (voir
// interpolateArrangementRelationship), d'où l'absence de préposition ici.
export enum EnumArrangements {
    AdjacentLeft = "est immédiatement à gauche de",
    AdjacentRight = "est immédiatement à droite de",
    Next = "est à côté de",
    NStepsLeft = "est # steps à gauche de",
    NStepsRight = "est # steps à droite de",
    Left = "est à gauche de",
    Right = "est à droite de",
    InFront = "est diamétralement opposé à", // non utilisé par l'agencement linéaire
};

// TRADUCTION FR : « quatre-vingts » perd son « s » devant un autre nombre,
// d'où « quatre-vingt-un » ; la liste s'arrête bien avant, mais la règle est
// rappelée ici pour une éventuelle extension.
export const NUMBER_WORDS = ["zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf"];

let strings: string[] = [];
export const getStrings = () => {
    const consonants = "QRSTVWXZ";
    const vowels = "AEIOU";

    if (strings.length === 0) {
        for (const c1 of consonants) {
            for (const v1 of vowels) {
                for (const c2 of consonants) {
                    strings.push(c1 + v1 + c2);
                }
            }
        }
    }

    return strings;
};

let emojis: string[] = [];
export const getEmojis = () => {
    if (emojis.length > 0) {
        return emojis;
    }

    const emojiRanges = [
        { start: 0x1F600, end: 0x1F64F }, // Emoticons
        { start: 0x1F300, end: 0x1F5FF }, // Misc Symbols and Pictographs
        // { start: 0x1F680, end: 0x1F6FF }, // Transport and Map Symbols
        // { start: 0x1F700, end: 0x1F77F }, // Alchemical Symbols
        // { start: 0x2600,  end: 0x26FF },  // Miscellaneous Symbols
    ];

    for (const range of emojiRanges) {
        for (let codePoint = range.start; codePoint <= range.end; codePoint++) {
            emojis.push(String.fromCodePoint(codePoint));
        }
    }

    return emojis;
};
getEmojis();

// TRADUCTION FR (remplace la liste anglaise du dépôt d'origine).
//
// Choix de conception : tous ces noms sont MASCULINS SINGULIERS. Les modèles de
// phrases français (« Tous les X sont des Y », « Aucun X n'est un Y »…)
// s'accordent donc toujours correctement, y compris lorsque les sujets sont des
// émojis ou des suites de lettres, pour lesquels le masculin est la valeur par
// défaut. Toute addition à cette liste doit respecter cette contrainte.
export const NOUNS = [
    "Abricot",
    "Accordéon",
    "Acrobate",
    "Aigle",
    "Aimant",
    "Alligator",
    "Alphabet",
    "Ananas",
    "Ancêtre",
    "Aquarium",
    "Arbre",
    "Archipel",
    "Architecte",
    "Arrosoir",
    "Artichaut",
    "Ascenseur",
    "Aspirateur",
    "Atelier",
    "Athlète",
    "Atlas",
    "Aubergiste",
    "Autobus",
    "Avion",
    "Avocat",
    "Balai",
    "Balcon",
    "Ballon",
    "Bambou",
    "Banc",
    "Bandeau",
    "Banquier",
    "Baobab",
    "Baromètre",
    "Barrage",
    "Bateau",
    "Bâtiment",
    "Bâton",
    "Beffroi",
    "Berger",
    "Bijou",
    "Billet",
    "Biscuit",
    "Bocal",
    "Bois",
    "Bonnet",
    "Bouchon",
    "Bouclier",
    "Bouquet",
    "Bourdon",
    "Bouton",
    "Bracelet",
    "Brouillard",
    "Buisson",
    "Bureau",
    "Cabanon",
    "Câble",
    "Cactus",
    "Cadeau",
    "Cadran",
    "Cahier",
    "Caillou",
    "Calendrier",
    "Camion",
    "Canal",
    "Canapé",
    "Canard",
    "Cargo",
    "Carnet",
    "Carrefour",
    "Carrosse",
    "Cartable",
    "Carton",
    "Casque",
    "Castor",
    "Cerf",
    "Chalet",
    "Chameau",
    "Champignon",
    "Chandelier",
    "Chantier",
    "Chapeau",
    "Charbon",
    "Chariot",
    "Chasseur",
    "Château",
    "Chaudron",
    "Chemin",
    "Chêne",
    "Cheval",
    "Chevalier",
    "Chiffon",
    "Chiffre",
    "Chocolat",
    "Cimetière",
    "Cinéma",
    "Ciseau",
    "Citron",
    "Clavier",
    "Clocher",
    "Cocon",
    "Coffre",
    "Collier",
    "Concert",
    "Concombre",
    "Continent",
    "Corbeau",
    "Cordage",
    "Corridor",
    "Costume",
    "Couloir",
    "Couteau",
    "Couvercle",
    "Crapaud",
    "Crayon",
    "Cristal",
    "Crocodile",
    "Croissant",
    "Cube",
    "Cuivre",
    "Cyclone",
    "Dauphin",
    "Débarcadère",
    "Dessin",
    "Diamant",
    "Dictionnaire",
    "Dinosaure",
    "Disque",
    "Dolmen",
    "Domino",
    "Donjon",
    "Dossier",
    "Dragon",
    "Drapeau",
    "Écran",
    "Écrivain",
    "Édifice",
    "Éléphant",
    "Emblème",
    "Entonnoir",
    "Épouvantail",
    "Escabeau",
    "Escalier",
    "Escargot",
    "Étang",
    "Éventail",
    "Fantôme",
    "Fauteuil",
    "Ferry",
    "Feutre",
    "Filet",
    "Flacon",
    "Flambeau",
    "Flamant",
    "Flocon",
    "Fossé",
    "Foulard",
    "Four",
    "Fourneau",
    "Foyer",
    "Fromage",
    "Fusain",
    "Galet",
    "Gant",
    "Garage",
    "Gardien",
    "Gâteau",
    "Général",
    "Genévrier",
    "Geyser",
    "Gibier",
    "Glacier",
    "Globe",
    "Gobelet",
    "Goéland",
    "Gouffre",
    "Gouvernail",
    "Grain",
    "Grenier",
    "Grillon",
    "Guidon",
    "Hameau",
    "Hangar",
    "Harnais",
    "Hérisson",
    "Héron",
    "Hibou",
    "Hippocampe",
    "Horizon",
    "Hublot",
    "Igloo",
    "Immeuble",
    "Incendie",
    "Index",
    "Insecte",
    "Instrument",
    "Interrupteur",
    "Iceberg",
    "Jardin",
    "Jaguar",
    "Javelot",
    "Jeton",
    "Jongleur",
    "Journal",
    "Judoka",
    "Jumelle",
    "Kayak",
    "Kiosque",
    "Koala",
    "Laboratoire",
    "Labyrinthe",
    "Lacet",
    "Lampadaire",
    "Landau",
    "Lapin",
    "Lavabo",
    "Lévrier",
    "Lexique",
    "Lézard",
    "Lierre",
    "Lion",
    "Livre",
    "Losange",
    "Loup",
    "Lustre",
    "Manoir",
    "Manteau",
    "Marbre",
    "Marché",
    "Marteau",
    "Masque",
    "Mât",
    "Matelas",
    "Menuisier",
    "Méridien",
    "Métal",
    "Météore",
    "Meuble",
    "Microscope",
    "Miel",
    "Minerai",
    "Miroir",
    "Modèle",
    "Monument",
    "Morceau",
    "Moteur",
    "Moulin",
    "Mouton",
    "Mur",
    "Musée",
    "Nautile",
    "Navire",
    "Nénuphar",
    "Nid",
    "Nuage",
    "Numéro",
    "Obélisque",
    "Océan",
    "Œillet",
    "Oiseau",
    "Olivier",
    "Orage",
    "Orchestre",
    "Ordinateur",
    "Oreiller",
    "Orteil",
    "Ours",
    "Ouvrage",
    "Palais",
    "Panier",
    "Panneau",
    "Paquebot",
    "Parachute",
    "Paratonnerre",
    "Parapluie",
    "Parc",
    "Parchemin",
    "Pavillon",
    "Paysage",
    "Peigne",
    "Pélican",
    "Pendule",
    "Perroquet",
    "Phare",
    "Piano",
    "Pigeon",
    "Pilier",
    "Pinceau",
    "Pingouin",
    "Placard",
    "Plafond",
    "Planeur",
    "Platane",
    "Plateau",
    "Pochoir",
    "Poisson",
    "Pommier",
    "Pont",
    "Portail",
    "Potager",
    "Poteau",
    "Poulailler",
    "Poumon",
    "Presse-papier",
    "Prisme",
    "Projecteur",
    "Pupitre",
    "Puzzle",
    "Pylône",
    "Quai",
    "Quartier",
    "Radeau",
    "Radiateur",
    "Raisin",
    "Rameau",
    "Rempart",
    "Renard",
    "Réservoir",
    "Réverbère",
    "Rideau",
    "Robinet",
    "Rocher",
    "Rondin",
    "Rossignol",
    "Rouage",
    "Roseau",
    "Ruban",
    "Ruisseau",
    "Sablier",
    "Sac",
    "Salon",
    "Sanglier",
    "Sapin",
    "Satellite",
    "Saxophone",
    "Scarabée",
    "Sceau",
    "Sentier",
    "Serpent",
    "Seuil",
    "Sifflet",
    "Silo",
    "Singe",
    "Soldat",
    "Soleil",
    "Sommet",
    "Sondage",
    "Sous-marin",
    "Spectacle",
    "Squelette",
    "Stade",
    "Studio",
    "Stylo",
    "Sucre",
    "Tableau",
    "Tabouret",
    "Tambour",
    "Tapis",
    "Télescope",
    "Temple",
    "Tentacule",
    "Terrain",
    "Territoire",
    "Théâtre",
    "Ticket",
    "Tigre",
    "Tiroir",
    "Tissu",
    "Toboggan",
    "Tonneau",
    "Torrent",
    "Tournesol",
    "Tracteur",
    "Traîneau",
    "Trajet",
    "Trapèze",
    "Trésor",
    "Triangle",
    "Tribunal",
    "Tricycle",
    "Tunnel",
    "Tuyau",
    "Vaisseau",
    "Vélo",
    "Verger",
    "Verrou",
    "Vestibule",
    "Viaduc",
    "Vieillard",
    "Vignoble",
    "Village",
    "Violon",
    "Virage",
    "Visage",
    "Volcan",
    "Volet",
    "Voyageur",
    "Wagon",
    "Yacht",
    "Zèbre",
    "Zeppelin"
];
